export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  RESOURCE_HAS_DEPENDENCIES = 'RESOURCE_HAS_DEPENDENCIES',
  CANNOT_DELETE_SELF = 'CANNOT_DELETE_SELF',
  CANNOT_UPDATE_SELF_ROLE = 'CANNOT_UPDATE_SELF_ROLE',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  LOGOUT_FAILED = 'LOGOUT_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
  FAILED_TO_SEND_OTP = 'FAILED_TO_SEND_OTP',
}
